name: Deploy to Environment

on:
  push:
    branches:
      - master
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no root@68.183.109.108 << 'EOF'
          cd /root/tax-calculator
          git pull origin ${{ github.ref_name }}
          if [ "${{ github.ref_name }}" = "master" ]; then
            docker-compose down
            docker-compose up --build -d
          else
            docker-compose -f docker-compose.dev.yml down
            docker-compose -f docker-compose.dev.yml up --build -d
          fi
          EOF
